trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'iris'

steps:
- task: Docker@2
  displayName: Push
  inputs: 
    command: buildAndPush
    repository: andyashall/iris
    tags: latest

resources:         
  containers:
  - container: iris      
    type: ACR  
    azureSubscription: 758becc8-a4de-4d7d-931c-92a77ed63c9a
    resourceGroup: flask
    registry: aaFlask
    repository: iris
    trigger: 
      tags:
        include: 
        - production* 