trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'iris'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: docker.io
- task: Docker@2
  displayName: Push
  inputs: 
    command: buildAndPush
    repository: andyashall/iris
    tags: latest

# resources:         
#   containers:
#   - container: petStore      
#     type: ACR  
#     azureSubscription: ContosoARMConnection
#     resourceGroup: ContosoGroup
#     registry: petStoreRegistry
#     repository: myPets
#     trigger: 
#       tags:
#         include: 
#         - production* 