trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'iris'

# resources:         
#   containers:
#   - container: iris      
#     type: ACR  
#     azureSubscription: 758becc8-a4de-4d7d-931c-92a77ed63c9a
#     resourceGroup: flask
#     registry: aaFlask
#     repository: iris
#     trigger: 
#       tags:
#         include: 
#         - production* 

# steps:
# - task: Docker@2
#   displayName: Push
#   inputs: 
#     command: buildAndPush
#     repository: andyashall/iris
#     tags: latest

# - task: Docker@2
#   displayName: Build and push stage
#   jobs:  
#   - job: Build
#     displayName: Build job
#     pool:
#       vmImage: iris
steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: aaflask.azurecr.io/iris
    dockerfile: Dockerfile
    containerRegistry: aaflask.azurecr.io
        # tags: |
        #   latest

