trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'iris'

steps:
- task: Docker@2
  displayName: Push
  inputs: 
    command: buildAndPush
    repository: andyashall/iris
    tags: latest